
train:
  gradient_accumulation_steps: 2
  epochs: 1000
  save_dir: ./exps/Sphere_VAE
  log_interval: 100
  eval_interval: 5000

  learning_rate: 2.0e-4
  training_steps: 1000000
  betas: [0.8, 0.99]
  eps: 1.0e-9

data:
  sample_rate: &sample_rate 24000
  hop_size: 300
  train_scp_path: ./data/train.scp
  segment_size: 288000
  batch_size: 16
  devices: 1
  seed: 3333
  num_workers: 4

model:
  sample_rate: *sample_rate
  latent_dimension: 64
  seanet:
    channels: 1
    dimension: &dim 512
    causal: True
    n_filters: 64
    n_residual_layers: 1
    activation: ELU
    compress: 2
    dilation_base: 2
    disable_norm_outer_blocks: 0
    kernel_size: 7
    residual_kernel_size: 3
    last_kernel_size: 3
    norm: none
    pad_mode: constant
    ratios: [8, 6, 5, 4]
    true_skip: True
  transformer:
    d_model: *dim
    num_heads: 8
    num_layers: 8
    causal: True
    layer_scale: 0.01
    context: 250
    conv_layout: True
    max_period: 10000
    gating: none
    norm: layer_norm
    positional_embedding: rope
    dim_feedforward: 2048
    input_dimension: *dim
    output_dimensions: [*dim]

  d_model: *dim

  msstftd:
    in_channels: 1
    out_channels: 1
    filters: 32
    norm: weight_norm
    n_ffts: [206, 334, 542, 876, 1418, 2296]
    hop_lengths: [103, 167, 271, 438, 709, 1148]
    win_lengths: [206, 334, 542, 876, 1418, 2296]
    activation: LeakyReLU
    activation_params: {negative_slope: 0.3}
  msspec:
    sample_rate: *sample_rate
